import type { Message, TaskDelegation, CommunicationFlow, DecisionRecord } from './communication-schemas';

// ============================================================
// SAMPLE COMMUNICATION DATA
// ============================================================

export const sampleMessages: Message[] = [
  {
    id: 'msg-001',
    timestamp: new Date(Date.now() - 300000).toISOString(),
    from: 'main-ai',
    to: 'research-team',
    role: 'main_ai',
    type: 'task_delegation',
    channel: 'main_to_team',
    content: 'Research the latest developments in quantum computing and their potential impact on cryptography. Focus on post-quantum cryptographic algorithms.',
    priority: 'high',
    status: 'delivered',
    taskId: 'task-research-001',
    teamId: 'research',
  },
  {
    id: 'msg-002',
    timestamp: new Date(Date.now() - 240000).toISOString(),
    from: 'research-team',
    to: 'main-ai',
    role: 'team_lead',
    type: 'acknowledgment',
    channel: 'team_to_main',
    content: 'Task received. Delegating to 5 research agents for parallel analysis.',
    status: 'delivered',
    taskId: 'task-research-001',
    teamId: 'research',
    responseTo: 'msg-001',
  },
  {
    id: 'msg-003',
    timestamp: new Date(Date.now() - 180000).toISOString(),
    from: 'research-01',
    to: 'research-team',
    role: 'agent',
    type: 'status_update',
    channel: 'agent_to_team',
    content: 'Analyzing NIST post-quantum cryptography standards. Progress: 40%',
    status: 'delivered',
    taskId: 'task-research-001',
    teamId: 'research',
    agentId: 'research-01',
  },
  {
    id: 'msg-004',
    timestamp: new Date(Date.now() - 120000).toISOString(),
    from: 'research-03',
    to: 'research-team',
    role: 'agent',
    type: 'task_result',
    channel: 'agent_to_team',
    content: 'Completed analysis of lattice-based cryptography. Key finding: CRYSTALS-Kyber shows promising resistance to quantum attacks with efficient key sizes.',
    status: 'delivered',
    taskId: 'task-research-001',
    teamId: 'research',
    agentId: 'research-03',
    metadata: { confidence: 0.92, tokens: 2340 },
  },
  {
    id: 'msg-005',
    timestamp: new Date(Date.now() - 60000).toISOString(),
    from: 'main-ai',
    to: 'code-team',
    role: 'main_ai',
    type: 'task_delegation',
    channel: 'main_to_team',
    content: 'Implement a proof-of-concept post-quantum key exchange using CRYSTALS-Kyber algorithm. Include benchmarking against RSA-2048.',
    priority: 'high',
    status: 'sent',
    taskId: 'task-code-001',
    teamId: 'code',
  },
  {
    id: 'msg-006',
    timestamp: new Date(Date.now() - 30000).toISOString(),
    from: 'code-team',
    to: 'main-ai',
    role: 'team_lead',
    type: 'acknowledgment',
    channel: 'team_to_main',
    content: 'Task accepted. Assigning to 3 code agents. Estimated completion: 15 minutes.',
    status: 'delivered',
    taskId: 'task-code-001',
    teamId: 'code',
    responseTo: 'msg-005',
  },
  {
    id: 'msg-007',
    timestamp: new Date(Date.now() - 15000).toISOString(),
    from: 'main-ai',
    to: 'system',
    role: 'main_ai',
    type: 'synthesis_request',
    channel: 'system',
    content: 'Synthesize results from research team on post-quantum cryptography. Need executive summary with key recommendations.',
    priority: 'medium',
    status: 'processed',
    taskId: 'task-research-001',
  },
  {
    id: 'msg-008',
    timestamp: new Date(Date.now() - 5000).toISOString(),
    from: 'system',
    to: 'main-ai',
    role: 'system',
    type: 'synthesis_result',
    channel: 'system',
    content: '**Post-Quantum Cryptography Synthesis**\n\nKey Findings:\n• CRYSTALS-Kyber (lattice-based) is the most promising NIST standard\n• Hash-based signatures (SPHINCS+) offer long-term security\n• Migration timeline: 5-10 years for full adoption\n\nRecommendations:\n1. Begin hybrid implementation (RSA + post-quantum)\n2. Prioritize lattice-based algorithms for performance\n3. Update cryptographic libraries within 2 years',
    status: 'delivered',
    taskId: 'task-research-001',
    responseTo: 'msg-007',
    metadata: { agentCount: 5, totalTokens: 12450, confidence: 0.89 },
  },
];

export const sampleTaskDelegations: TaskDelegation[] = [
  {
    id: 'task-research-001',
    title: 'Post-Quantum Cryptography Research',
    description: 'Research latest developments in quantum computing and their impact on cryptography',
    team: 'research',
    priority: 'high',
    requirements: [
      'Analyze NIST post-quantum standards',
      'Evaluate lattice-based algorithms',
      'Assess migration timelines',
      'Provide implementation recommendations',
    ],
    context: 'Critical for future-proofing our security architecture',
    expectedOutput: 'Comprehensive research report with actionable recommendations',
    delegatedAt: new Date(Date.now() - 300000).toISOString(),
    delegatedBy: 'main-ai',
    status: 'completed',
    assignedAgents: ['research-01', 'research-02', 'research-03', 'research-04', 'research-05'],
    results: [
      {
        agentId: 'research-01',
        result: 'NIST has standardized 4 post-quantum algorithms: CRYSTALS-Kyber, CRYSTALS-Dilithium, FALCON, and SPHINCS+',
        confidence: 0.95,
        timestamp: new Date(Date.now() - 200000).toISOString(),
      },
      {
        agentId: 'research-02',
        result: 'Lattice-based algorithms offer the best performance/size ratio for most use cases',
        confidence: 0.88,
        timestamp: new Date(Date.now() - 180000).toISOString(),
      },
      {
        agentId: 'research-03',
        result: 'CRYSTALS-Kyber shows promising resistance to quantum attacks with efficient key sizes (800-1500 bytes)',
        confidence: 0.92,
        timestamp: new Date(Date.now() - 120000).toISOString(),
      },
      {
        agentId: 'research-04',
        result: 'Migration timeline estimated at 5-10 years for full industry adoption',
        confidence: 0.85,
        timestamp: new Date(Date.now() - 100000).toISOString(),
      },
      {
        agentId: 'research-05',
        result: 'Hybrid approach (classical + post-quantum) recommended for transition period',
        confidence: 0.90,
        timestamp: new Date(Date.now() - 80000).toISOString(),
      },
    ],
    synthesizedResult: 'Post-quantum cryptography is ready for implementation. CRYSTALS-Kyber is the leading candidate for key exchange, with lattice-based algorithms offering the best balance of security and performance. Recommend hybrid implementation starting within 2 years.',
    synthesizedAt: new Date(Date.now() - 5000).toISOString(),
  },
  {
    id: 'task-code-001',
    title: 'Post-Quantum Key Exchange Implementation',
    description: 'Implement proof-of-concept post-quantum key exchange using CRYSTALS-Kyber',
    team: 'code',
    priority: 'high',
    requirements: [
      'Implement CRYSTALS-Kyber key exchange',
      'Include benchmarking against RSA-2048',
      'Write comprehensive tests',
      'Document performance characteristics',
    ],
    context: 'Based on research findings from task-research-001',
    expectedOutput: 'Working implementation with benchmarks and documentation',
    delegatedAt: new Date(Date.now() - 60000).toISOString(),
    delegatedBy: 'main-ai',
    status: 'in_progress',
    assignedAgents: ['code-01', 'code-02', 'code-03'],
  },
];

export const sampleCommunicationFlows: CommunicationFlow[] = [
  {
    id: 'flow-001',
    timestamp: new Date(Date.now() - 300000).toISOString(),
    flow: [
      { step: 1, from: 'main-ai', to: 'research-team', action: 'Task delegation', duration: 50, status: 'completed' },
      { step: 2, from: 'research-team', to: 'main-ai', action: 'Acknowledgment', duration: 120, status: 'completed' },
      { step: 3, from: 'research-team', to: 'agents', action: 'Task distribution', duration: 80, status: 'completed' },
      { step: 4, from: 'agents', to: 'research-team', action: 'Parallel research (5 agents)', duration: 180000, status: 'completed' },
      { step: 5, from: 'research-team', to: 'main-ai', action: 'Results submission', duration: 200, status: 'completed' },
      { step: 6, from: 'main-ai', to: 'system', action: 'Synthesis request', duration: 100, status: 'completed' },
      { step: 7, from: 'system', to: 'main-ai', action: 'Synthesized results', duration: 2500, status: 'completed' },
    ],
    totalDuration: 183050,
    status: 'completed',
  },
  {
    id: 'flow-002',
    timestamp: new Date(Date.now() - 60000).toISOString(),
    flow: [
      { step: 1, from: 'main-ai', to: 'code-team', action: 'Task delegation', duration: 45, status: 'completed' },
      { step: 2, from: 'code-team', to: 'main-ai', action: 'Acknowledgment', duration: 95, status: 'completed' },
      { step: 3, from: 'code-team', to: 'agents', action: 'Task distribution', duration: 60, status: 'completed' },
      { step: 4, from: 'agents', to: 'code-team', action: 'Implementation in progress', duration: 0, status: 'pending' },
    ],
    totalDuration: 0,
    status: 'in_progress',
  },
];

export const sampleDecisions: DecisionRecord[] = [
  {
    id: 'decision-001',
    timestamp: new Date(Date.now() - 5000).toISOString(),
    decision: 'Proceed with CRYSTALS-Kyber implementation',
    rationale: 'Research synthesis shows CRYSTALS-Kyber is the most promising NIST-standardized post-quantum algorithm with optimal performance/size ratio',
    basedOn: ['task-research-001', 'msg-008'],
    confidence: 0.89,
    impact: 'Future-proofs cryptographic infrastructure against quantum attacks',
    nextSteps: [
      'Complete proof-of-concept implementation',
      'Benchmark against current RSA-2048',
      'Plan hybrid migration strategy',
      'Update security architecture documentation',
    ],
  },
];

// ============================================================
// COMMUNICATION SIMULATION
// ============================================================

export function generateRealtimeMessage(): Message {
  const templates = [
    {
      from: 'research-02',
      to: 'research-team',
      role: 'agent' as const,
      type: 'status_update' as const,
      channel: 'agent_to_team' as const,
      content: 'Cross-referencing quantum threat models. Progress: 65%',
    },
    {
      from: 'code-01',
      to: 'code-team',
      role: 'agent' as const,
      type: 'status_update' as const,
      channel: 'agent_to_team' as const,
      content: 'CRYSTALS-Kyber key generation module complete. Starting integration tests.',
    },
    {
      from: 'architect-03',
      to: 'architect-team',
      role: 'agent' as const,
      type: 'task_result' as const,
      channel: 'agent_to_team' as const,
      content: 'Hybrid cryptography architecture designed. Supports seamless transition from RSA to post-quantum.',
    },
    {
      from: 'algorithm-02',
      to: 'algorithm-team',
      role: 'agent' as const,
      type: 'status_update' as const,
      channel: 'agent_to_team' as const,
      content: 'Optimizing lattice reduction algorithm. Performance improvement: 23%',
    },
    {
      from: 'frontend-04',
      to: 'frontend-team',
      role: 'agent' as const,
      type: 'task_result' as const,
      channel: 'agent_to_team' as const,
      content: 'Security dashboard UI complete. Real-time threat visualization implemented.',
    },
    {
      from: 'backend-01',
      to: 'backend-team',
      role: 'agent' as const,
      type: 'status_update' as const,
      channel: 'agent_to_team' as const,
      content: 'API endpoint for certificate rotation deployed. Testing in progress.',
    },
  ];

  const template = templates[Math.floor(Math.random() * templates.length)];
  const teamId = template.from.split('-')[0];

  return {
    id: `msg-realtime-${Date.now()}`,
    timestamp: new Date().toISOString(),
    from: template.from,
    to: template.to,
    role: template.role,
    type: template.type,
    channel: template.channel,
    content: template.content,
    status: 'delivered',
    teamId,
    agentId: template.from.includes('-') ? template.from : undefined,
  };
}
