import type { Certificate, SecurityRule, SecurityHeader, SecurityEvent, AntiFingerprintConfig, SecurityMetrics } from './security-schemas';

// ============================================================
// TLS/SSL CERTIFICATES (6 Teams × Custom CA)
// ============================================================

export const certificates: Certificate[] = [
  {
    id: 'cert-research-001',
    team: 'research',
    type: 'mutual-tls',
    commonName: 'research.swarm.mcp.internal',
    issuer: 'MCP Swarm Internal CA',
    serialNumber: '0A:1B:2C:3D:4E:5F:6A:7B',
    validFrom: '2026-01-15T00:00:00Z',
    validTo: '2027-01-15T00:00:00Z',
    keySize: 4096,
    signatureAlgorithm: 'SHA384withRSA',
    fingerprint: 'A1:B2:C3:D4:E5:F6:01:23:45:67:89:AB:CD:EF:01:23',
    status: 'valid',
    daysUntilExpiry: 287,
    autoRenew: true,
    pinned: true,
  },
  {
    id: 'cert-code-001',
    team: 'code',
    type: 'mutual-tls',
    commonName: 'code.swarm.mcp.internal',
    issuer: 'MCP Swarm Internal CA',
    serialNumber: '1B:2C:3D:4E:5F:6A:7B:8C',
    validFrom: '2026-01-15T00:00:00Z',
    validTo: '2027-01-15T00:00:00Z',
    keySize: 4096,
    signatureAlgorithm: 'SHA384withRSA',
    fingerprint: 'B2:C3:D4:E5:F6:01:23:45:67:89:AB:CD:EF:01:23:45',
    status: 'valid',
    daysUntilExpiry: 287,
    autoRenew: true,
    pinned: true,
  },
  {
    id: 'cert-architect-001',
    team: 'architect',
    type: 'mutual-tls',
    commonName: 'architect.swarm.mcp.internal',
    issuer: 'MCP Swarm Internal CA',
    serialNumber: '2C:3D:4E:5F:6A:7B:8C:9D',
    validFrom: '2026-01-15T00:00:00Z',
    validTo: '2027-01-15T00:00:00Z',
    keySize: 4096,
    signatureAlgorithm: 'SHA384withRSA',
    fingerprint: 'C3:D4:E5:F6:01:23:45:67:89:AB:CD:EF:01:23:45:67',
    status: 'valid',
    daysUntilExpiry: 287,
    autoRenew: true,
    pinned: true,
  },
  {
    id: 'cert-algorithm-001',
    team: 'algorithm',
    type: 'mutual-tls',
    commonName: 'algorithm.swarm.mcp.internal',
    issuer: 'MCP Swarm Internal CA',
    serialNumber: '3D:4E:5F:6A:7B:8C:9D:0E',
    validFrom: '2026-01-15T00:00:00Z',
    validTo: '2027-01-15T00:00:00Z',
    keySize: 4096,
    signatureAlgorithm: 'SHA384withRSA',
    fingerprint: 'D4:E5:F6:01:23:45:67:89:AB:CD:EF:01:23:45:67:89',
    status: 'valid',
    daysUntilExpiry: 287,
    autoRenew: true,
    pinned: true,
  },
  {
    id: 'cert-frontend-001',
    team: 'frontend',
    type: 'mutual-tls',
    commonName: 'frontend.swarm.mcp.internal',
    issuer: 'MCP Swarm Internal CA',
    serialNumber: '4E:5F:6A:7B:8C:9D:0E:1F',
    validFrom: '2026-01-15T00:00:00Z',
    validTo: '2027-01-15T00:00:00Z',
    keySize: 4096,
    signatureAlgorithm: 'SHA384withRSA',
    fingerprint: 'E5:F6:01:23:45:67:89:AB:CD:EF:01:23:45:67:89:AB',
    status: 'valid',
    daysUntilExpiry: 287,
    autoRenew: true,
    pinned: true,
  },
  {
    id: 'cert-backend-001',
    team: 'backend',
    type: 'mutual-tls',
    commonName: 'backend.swarm.mcp.internal',
    issuer: 'MCP Swarm Internal CA',
    serialNumber: '5F:6A:7B:8C:9D:0E:1F:2A',
    validFrom: '2026-01-15T00:00:00Z',
    validTo: '2027-01-15T00:00:00Z',
    keySize: 4096,
    signatureAlgorithm: 'SHA384withRSA',
    fingerprint: 'F6:01:23:45:67:89:AB:CD:EF:01:23:45:67:89:AB:CD',
    status: 'valid',
    daysUntilExpiry: 287,
    autoRenew: true,
    pinned: true,
  },
  // Root CA Certificate
  {
    id: 'cert-root-ca',
    team: 'system',
    type: 'ssl',
    commonName: 'MCP Swarm Root CA',
    issuer: 'MCP Swarm Root CA (Self-Signed)',
    serialNumber: '00:00:00:00:00:00:00:01',
    validFrom: '2025-01-01T00:00:00Z',
    validTo: '2035-01-01T00:00:00Z',
    keySize: 8192,
    signatureAlgorithm: 'SHA512withRSA',
    fingerprint: '00:11:22:33:44:55:66:77:88:99:AA:BB:CC:DD:EE:FF',
    status: 'valid',
    daysUntilExpiry: 3287,
    autoRenew: false,
    pinned: true,
  },
];

// ============================================================
// SECURITY RULES & GUARDRAILS
// ============================================================

export const securityRules: SecurityRule[] = [
  {
    id: 'rule-001',
    name: 'Rate Limiting - API Endpoints',
    description: 'Limit API requests to 100/minute per IP to prevent brute force',
    category: 'network',
    severity: 'high',
    enabled: true,
    action: 'rate_limit',
    conditions: ['requests > 100/min', 'same IP address'],
    lastTriggered: new Date(Date.now() - 3600000).toISOString(),
    triggerCount: 234,
  },
  {
    id: 'rule-002',
    name: 'SQL Injection Prevention',
    description: 'Block requests containing SQL injection patterns',
    category: 'application',
    severity: 'critical',
    enabled: true,
    action: 'block',
    conditions: ['UNION SELECT', 'DROP TABLE', 'OR 1=1', '-- comment'],
    lastTriggered: new Date(Date.now() - 7200000).toISOString(),
    triggerCount: 89,
  },
  {
    id: 'rule-003',
    name: 'XSS Prevention',
    description: 'Block requests containing cross-site scripting payloads',
    category: 'application',
    severity: 'critical',
    enabled: true,
    action: 'block',
    conditions: ['<script>', 'javascript:', 'onerror=', 'onload='],
    lastTriggered: new Date(Date.now() - 1800000).toISOString(),
    triggerCount: 156,
  },
  {
    id: 'rule-004',
    name: 'Path Traversal Prevention',
    description: 'Block directory traversal attempts',
    category: 'application',
    severity: 'critical',
    enabled: true,
    action: 'block',
    conditions: ['../', '..\\', '%2e%2e', '/etc/passwd'],
    lastTriggered: new Date(Date.now() - 5400000).toISOString(),
    triggerCount: 45,
  },
  {
    id: 'rule-005',
    name: 'Agent Isolation Enforcement',
    description: 'Ensure agents cannot access other team resources',
    category: 'access',
    severity: 'high',
    enabled: true,
    action: 'block',
    conditions: ['cross-team access', 'unauthorized resource'],
    lastTriggered: new Date(Date.now() - 900000).toISOString(),
    triggerCount: 12,
  },
  {
    id: 'rule-006',
    name: 'Certificate Pinning Validation',
    description: 'Verify certificate fingerprints match pinned values',
    category: 'encryption',
    severity: 'critical',
    enabled: true,
    action: 'block',
    conditions: ['fingerprint mismatch', 'untrusted certificate'],
    lastTriggered: null,
    triggerCount: 0,
  },
  {
    id: 'rule-007',
    name: 'TLS Version Enforcement',
    description: 'Reject connections using TLS < 1.3',
    category: 'encryption',
    severity: 'high',
    enabled: true,
    action: 'block',
    conditions: ['TLS 1.0', 'TLS 1.1', 'TLS 1.2'],
    lastTriggered: new Date(Date.now() - 86400000).toISOString(),
    triggerCount: 7,
  },
  {
    id: 'rule-008',
    name: 'Fingerprint Detection Block',
    description: 'Block known fingerprinting scripts and techniques',
    category: 'application',
    severity: 'medium',
    enabled: true,
    action: 'block',
    conditions: ['fingerprint.js', 'tracking pixel', 'canvas readout'],
    lastTriggered: new Date(Date.now() - 600000).toISOString(),
    triggerCount: 342,
  },
  {
    id: 'rule-009',
    name: 'Anomalous Behavior Detection',
    description: 'Alert on unusual agent behavior patterns',
    category: 'monitoring',
    severity: 'medium',
    enabled: true,
    action: 'alert',
    conditions: ['unusual request volume', 'abnormal response time', 'unexpected data access'],
    lastTriggered: new Date(Date.now() - 120000).toISOString(),
    triggerCount: 23,
  },
  {
    id: 'rule-010',
    name: 'Data Exfiltration Prevention',
    description: 'Monitor and block unusual outbound data transfers',
    category: 'data',
    severity: 'critical',
    enabled: true,
    action: 'quarantine',
    conditions: ['large outbound transfer', 'unusual destination', 'encoded payload'],
    lastTriggered: null,
    triggerCount: 0,
  },
  {
    id: 'rule-011',
    name: 'Header Injection Prevention',
    description: 'Block requests with header injection attempts',
    category: 'application',
    severity: 'high',
    enabled: true,
    action: 'block',
    conditions: ['\\r\\n', 'CRLF injection', 'header overflow'],
    lastTriggered: new Date(Date.now() - 43200000).toISOString(),
    triggerCount: 34,
  },
  {
    id: 'rule-012',
    name: 'API Key Rotation Enforcement',
    description: 'Force API key rotation every 30 days',
    category: 'access',
    severity: 'high',
    enabled: true,
    action: 'alert',
    conditions: ['key age > 30 days', 'no rotation scheduled'],
    lastTriggered: new Date(Date.now() - 172800000).toISOString(),
    triggerCount: 6,
  },
];

// ============================================================
// SECURITY HEADERS
// ============================================================

export const securityHeaders: SecurityHeader[] = [
  {
    name: 'Strict-Transport-Security',
    value: 'max-age=63072000; includeSubDomains; preload',
    description: 'Force HTTPS for 2 years with subdomains and preload',
    enforced: true,
    critical: true,
  },
  {
    name: 'Content-Security-Policy',
    value: "default-src 'self'; script-src 'self' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self' wss:; frame-ancestors 'none'; base-uri 'self'; form-action 'self';",
    description: 'Strict CSP preventing XSS, clickjacking, and data injection',
    enforced: true,
    critical: true,
  },
  {
    name: 'X-Content-Type-Options',
    value: 'nosniff',
    description: 'Prevent MIME type sniffing attacks',
    enforced: true,
    critical: true,
  },
  {
    name: 'X-Frame-Options',
    value: 'DENY',
    description: 'Prevent clickjacking by disabling all framing',
    enforced: true,
    critical: true,
  },
  {
    name: 'X-XSS-Protection',
    value: '1; mode=block',
    description: 'Enable browser XSS filter in block mode',
    enforced: true,
    critical: false,
  },
  {
    name: 'Referrer-Policy',
    value: 'strict-origin-when-cross-origin',
    description: 'Limit referrer information to origin only',
    enforced: true,
    critical: false,
  },
  {
    name: 'Permissions-Policy',
    value: 'camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()',
    description: 'Disable all sensitive browser APIs',
    enforced: true,
    critical: true,
  },
  {
    name: 'Cross-Origin-Opener-Policy',
    value: 'same-origin',
    description: 'Isolate browsing context to same origin',
    enforced: true,
    critical: true,
  },
  {
    name: 'Cross-Origin-Embedder-Policy',
    value: 'require-corp',
    description: 'Require CORP/CORS for all cross-origin resources',
    enforced: true,
    critical: true,
  },
  {
    name: 'Cross-Origin-Resource-Policy',
    value: 'same-origin',
    description: 'Restrict resource loading to same origin',
    enforced: true,
    critical: true,
  },
  {
    name: 'X-Permitted-Cross-Domain-Policies',
    value: 'none',
    description: 'Disable Flash/PDF cross-domain policies',
    enforced: true,
    critical: false,
  },
  {
    name: 'Cache-Control',
    value: 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0',
    description: 'Prevent caching of sensitive data',
    enforced: true,
    critical: true,
  },
  {
    name: 'Pragma',
    value: 'no-cache',
    description: 'HTTP/1.0 cache control',
    enforced: true,
    critical: false,
  },
  {
    name: 'X-DNS-Prefetch-Control',
    value: 'off',
    description: 'Disable DNS prefetching to prevent information leakage',
    enforced: true,
    critical: false,
  },
  {
    name: 'X-Download-Options',
    value: 'noopen',
    description: 'Prevent IE from executing downloads in site context',
    enforced: true,
    critical: false,
  },
  {
    name: 'Server',
    value: '',
    description: 'Remove server identification header',
    enforced: true,
    critical: true,
  },
  {
    name: 'X-Powered-By',
    value: '',
    description: 'Remove technology identification header',
    enforced: true,
    critical: true,
  },
  {
    name: 'X-Custom-Security-Token',
    value: 'MCP-SWARM-v1-{HMAC_SHA384}',
    description: 'Custom anti-tampering token with HMAC signature',
    enforced: true,
    critical: true,
  },
];

// ============================================================
// ANTI-FINGERPRINT CONFIGURATION
// ============================================================

export const antiFingerprintConfig: AntiFingerprintConfig = {
  canvas: true,
  webgl: true,
  audio: true,
  fonts: true,
  screen: true,
  timezone: true,
  language: true,
  plugins: true,
  webrtc: true,
  hardware: true,
};

// ============================================================
// SECURITY EVENTS
// ============================================================

export function generateSecurityEvents(): SecurityEvent[] {
  const events: SecurityEvent[] = [];
  const types: SecurityEvent['type'][] = ['blocked', 'alert', 'warning', 'info', 'success'];
  const sources = ['WAF', 'IDS', 'Rate Limiter', 'Cert Validator', 'Anti-Fingerprint', 'IP Filter', 'Input Validator'];
  const details = [
    'SQL injection attempt blocked from 192.168.1.45',
    'XSS payload detected and neutralized',
    'Rate limit exceeded for IP 10.0.0.23',
    'Certificate fingerprint verified successfully',
    'Canvas fingerprint noise injected',
    'WebRTC leak prevented',
    'Suspicious user agent blocked',
    'Path traversal attempt blocked',
    'TLS 1.0 connection rejected',
    'Header injection attempt blocked',
    'Agent isolation violation prevented',
    'Data exfiltration attempt quarantined',
    'Brute force attack mitigated',
    'CSRF token validated',
    'CORS policy enforced',
  ];
  const severities: SecurityEvent['severity'][] = ['critical', 'high', 'medium', 'low', 'info'];

  for (let i = 0; i < 30; i++) {
    events.push({
      id: `sec-event-${i}`,
      timestamp: new Date(Date.now() - Math.random() * 86400000).toISOString(),
      type: types[Math.floor(Math.random() * types.length)],
      source: sources[Math.floor(Math.random() * sources.length)],
      target: `team-${['research', 'code', 'architect', 'algorithm', 'frontend', 'backend'][Math.floor(Math.random() * 6)]}`,
      rule: `rule-${String(Math.floor(Math.random() * 12) + 1).padStart(3, '0')}`,
      details: details[Math.floor(Math.random() * details.length)],
      ip: `${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}`,
      userAgent: 'Mozilla/5.0 (Secure; Protected)',
      severity: severities[Math.floor(Math.random() * severities.length)],
      resolved: Math.random() > 0.3,
    });
  }

  return events.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
}

// ============================================================
// SECURITY METRICS
// ============================================================

export const securityMetrics: SecurityMetrics = {
  totalBlocked: 7834,
  totalAlerts: 1247,
  activeThreats: 3,
  securityScore: 97.8,
  certificatesValid: 7,
  certificatesExpiring: 0,
  rulesEnabled: 12,
  lastSecurityScan: new Date().toISOString(),
  encryptionStrength: 'AES-256-GCM + TLS 1.3',
  tlsVersion: 'TLS 1.3',
};
